### ISSUE TITLE
Severe Weather Outbreak Case Study description

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2021#106]
We're currently missing a description for the ["Severe Weather Outbreak Case Study" project](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html). I believe @mgrover1 added this one to the project ideas spreadsheet in the fall? If so, would you mind adding a description to describe what you had in mind?

**Comment by mgrover1** [comment]
I added in the description with the declarative notebook

**Comment by lesserwhirls** [comment]
Sweet! I missed that (haven't looked since other have jumped in to review)
