### ISSUE TITLE
Create a "Numpy (csv data)" Training Notebook

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2021#21]
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/dataAccess/` directory that covers reading in CSV data from a local file to assist workshop participants who choose to work on the following projects:
  * [`site/projects/climate_timeseries.md`](https://unidata.github.io/pyaos-ams-2021/projects/climate_timeseries.html)
  * [`site/projects/model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/model_vs_obs.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/dataAccess/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

**Comment by AodhanSweeney** [comment]
I can work on this one if no one else is on it yet

**Comment by AodhanSweeney** [comment]
Although this is called Numpy csv data, can we use the pandas read_csv() function? I googled for the numpy one, which is genfromtxt() but I think the pandas one is easier to use. Either way is fine with me!

**Comment by lesserwhirls** [comment]
Also tagging @dcamron to get his input.

**Comment by dopplershift** [comment]
Assuming we're talking CSV time series (or something columnar--just NOT csv-ified grids), Pandas is the right way to do things in Python in 2020.

Us old farts just got too comfortable dealing with the suboptimal tools in 2008. :wink:

**Comment by lesserwhirls** [comment]
Well...you're not wrong :-)

![yard](https://media.giphy.com/media/l0HlQz5f2TBEj7KY8/giphy.gif)

Ok, so let's switch this over to pandas :-)
