### ISSUE TITLE
Create a "Scipy" Training Notebook

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2021#22]
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/analysis/` directory that covers the use of Scipy for statistical analysis to assist workshop participants who choose to work on the following projects:
  * [`site/projects/adv_model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/adv_model_vs_obs.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/analysis/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

**Comment by lesserwhirls** [comment]
I'm wondering...do we need this one, or does Unidata/pyaos-ams-2021#28 cover the needs for the AMS workshop. Eventually, yeah, probably good to have a few bite-sized SciPy trainings, but for this workshop?

**Comment by lesserwhirls** [comment]
What do you think @jthielen - do you think Unidata/pyaos-ams-2021#28 covers what we need for this week?

**Comment by jthielen** [comment]
I was imagining that #28 was more focused on xarray operations (and not really using anything from scipy directly), whereas the scipy training notebook would be independent of xarray, and would cover things like basic signal/image processing and stats. However, I'm not sure if the timeline permits at this point to have such a dedicated notebook ready to go in time, so we may just have to go by without it? Although, [my Rossby wave example notebook](https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/abb703d829623a75526cbfb767ebcc015399ef4e/notebooks/analysis/rossby_waves.ipynb) uses scipy without really calling it out, so in the meantime I could update that to explain it a bit more and link out to the scipy documentation to learn more?

**Comment by lesserwhirls** [comment]
I think that sounds good. I was thinking that the use of SciPy for this workshop was minimal enough that it didn't require a dedicated scipy notebook. I'll go ahead and close this one out after I remove references from the site in a PR.
