### ISSUE TITLE
Create a "MetPy (unit-aware calculations)" Training Notebook

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2021#32]
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/analylsis/` directory that covers the ability of MetPy to perform unite-aware calculations to assist workshop participants who choose to work on the following projects:
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)
  * [`site/projects/severe_wx_outbreak.md`](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using the a nbviewer (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/analysis/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

**Comment by jthielen** [comment]
I think this would be redundant with https://github.com/Unidata/pyaos-ams-2021/issues/30 (MetPy Basic Calculations) and https://github.com/Unidata/pyaos-ams-2021/issues/29 (Pint unit-aware operations), unless I'm missing something?

**Comment by lesserwhirls** [comment]
_(sidenote: thank you for volunteering for those open notebook issues!)_

I think the thought here was a bite-sized training piece would be pint on its own, to set the foundation of sort for using units with MetPy, but I can see how MetPy with Units could cover it all. @dopplershift - what do you think?

**Comment by dopplershift** [comment]
My experience with teaching says that #29 is probably all we need here unless we're doing a Chem/Physics 101-style intro to units.

**Comment by lesserwhirls** [comment]
Oops...I totally misread this issue...

So the idea with this notebook was to have a demonstration of using MetPy and with Units. Something very simple, and only focused on Units (with pointers to the docs). The MetPy calculations would then focus on things that are available in the `metpy.calc` package (and subpackages) without digging into the basics of units. There was also a training notebook that was to cover straight up `pint`, but that one could probably be dropped in favor of this one.

**Comment by rpmanser** [comment]
I can grab this one and hammer it out tonight. So this should just be an introduction to units i.e., applying them to scalars and arrays, unit conversion, magnitude, and perhaps emphasizing that `metpy.calc` functions expect arguments with units?

**Comment by jthielen** [comment]
> I can grab this one and hammer it out tonight. So this should just be an introduction to units i.e., applying them to scalars and arrays, unit conversion, magnitude, and perhaps emphasizing that `metpy.calc` functions expect arguments with units?

Sounds good to me! Two gotchas that would probably also worth mentioning are masked arrays (make sure to use the Quantity constructor) and temperature units (watch out for differences of degrees Celsius or Fahrenheit).
