### ISSUE TITLE
Create a "MetPy (with xarray)" Training Notebook

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2021#33]
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/analysis/` directory that covers the use of `xarray` in `MetPy` to assist workshop participants who choose to work on the following projects:
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)
  * [`site/projects/rossby_wave_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/rossby_wave_analysis.html)
  * [`site/projects/severe_wx_outbreak.md`](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/analysis/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

**Comment by jthielen** [comment]
I can work on this based on what I did for https://github.com/Unidata/MetPy/pull/1605.
