### ISSUE TITLE
Create a "Isentropic Analysis" Training Notebook

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2021#35]
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/met_background_material/` directory that covers the basics of isentropic analysis in meteorology to assist workshop participants who choose to work on the following projects:
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/met_background_material/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

**Comment by tjwixtrom** [comment]
I should have some time this week to work on a few of these. Are we just looking for an example analysis notebook? If so, this  [notebook](https://unidata.github.io/MetPy/latest/examples/isentropic_example.html#sphx-glr-examples-isentropic-example-py) should work with a few modifications.

**Comment by lesserwhirls** [comment]
Hi @tjwixtrom - that's a great question! Ideally these training notebooks are supposed to be "bite-sized" (focused on an individual component of a project), but it's a bit tough to do a 'bite-sized". However, based on some things that @LProx2020 did in her PR, we added a section to the project idea pages called "Related Comprehensive Notebooks" (see [here](https://unidata.github.io/pyaos-ams-2021/projects/intro_timeseries.html)), and this notebook would be great to add to the Isentropic Analysis [project page](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html).

What I originally had in mind for the notebook in this issue specifically was a sort of "meteorological overview" of isentropic analysis, but maybe that's too big of a lift to do in a "bite-sized" way?

**Comment by tjwixtrom** [comment]
Ok, I can take a stab at that, I think it should be possible to create a notebook with a short explanation and simple plot example and then also include a link to the longer more detailed [example](https://unidata.github.io/python-gallery/examples/Isentropic_Interpolation.html#sphx-glr-examples-isentropic-interpolation-py) in the python gallery which includes pulling data with Siphon, etc.

**Comment by lesserwhirls** [comment]
Awesome - sounds like a plan @tjwixtrom!

**Comment by dopplershift** [comment]
Closed by #71.
