### ISSUE TITLE
Create a "MetPy (SkewT)" Training Notebook

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2021#41]
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/visualization/` directory that covers creating Skew-T diagrams using `MetPy` to assist workshop participants who choose to work on the following projects:
  * [`site/projects/severe_wx_outbreak.md`](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/visualization/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

**Comment by lesserwhirls** [comment]
@mwilson14 volunteered to take this one, but I cannot assign his name to the issue.

**Comment by mwilson14** [comment]
Oops! I think GitHub was grumpy because I hadn't set up two-factor yet. Maybe it will work now?

**Comment by lesserwhirls** [comment]
That did it! Good to know that's the secret sauce! 😆

**Comment by srcarter3** [comment]
Thanks for your work so far on this @mwilson14!  Please don't forget to add a description and link in the resources and on the appropriate projects pages.
Also, it might be a little tricky to get the proper link since the notebook file has a space in the name.  I might suggest changing the name to use '-' instead of a space for simplicity.

**Comment by dopplershift** [comment]
MetPy Skew-T is merged (#93) and linked.
