### ISSUE TITLE
Create a "Notebook widgets" Training Notebook

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2021#44]
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/notebook_enhancements/` directory that covers the basic of using widgets, such as drop down selection boxes and other interactive elements, inside Jupyter Notebooks, to assist workshop participants who choose to work on the following projects:
  * [`site/projects/adv_model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/adv_model_vs_obs.html)

Once the notebook is complete, be sure to do the following:

* [x] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [x] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/notebook_enhancements/<training-notebook-name>.ipynb`):
  * [x] the project page for each project idea listed above
  * [x] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [x] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

**Comment by haileyajohnson** [comment]
closed by #78
